### ISSUE TITLE
Include types for the package

### ISSUE THREAD

**Issue by shrihari-prakash** [node-oauth/express-oauth-server#10]
For the express-oauth-server counterpart from oauthjs, there are types specified in DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-oauth-server/index.d.ts

However for this project, there is nothing of that sort. It would be good to include the typings file from DefinitelyTypes and point to it in package.json. Right now, when I import the package on TypeScript projects, it would complain that there is no types associated:

![image](https://github.com/node-oauth/express-oauth-server/assets/35889246/58fee2c0-1b49-414e-b93c-8e154b800db0)

**Comment by shrihari-prakash** [comment]
Hello @jankapunkt , @HappyZombies ,
I added types for this package from DefinitelyTyped. Could you please review and merge this if you feel it's okay? https://github.com/node-oauth/express-oauth-server/pull/11

**Comment by jankapunkt** [comment]
published in [3.0.1](https://github.com/node-oauth/express-oauth-server/releases/tag/v3.0.1)
