### ISSUE TITLE
Remove express as a dependency

### ISSUE THREAD

**Issue by HappyZombies** [node-oauth/express-oauth-server#13]
I must've just missed this, but there's no reason to include express as a dependeny. Sure people will use it for express, but by removing express we reduce our dependency map on our side

**Comment by jankapunkt** [comment]
Hey @HappyZombies I just updated the deps from the original and thought this is all good, keeping it stable etc.

 If this dependency isn't required in the code then let's remove it or make it dev dependency if required for Tests.

**Comment by jankapunkt** [comment]
Implemented in [v4.0.0-rc.0](https://github.com/node-oauth/express-oauth-server/releases/tag/v4.0.0-rc.0)
