### ISSUE TITLE
Is this going to replace oauthjs/express-oauth-server ? 

### ISSUE THREAD

**Issue by relu91** [node-oauth/express-oauth-server#5]
Just passing by and I was wondering if this fork will be published under https://www.npmjs.com/package/express-oauth-server soon or after. With https://github.com/eclipse/thingweb.node-wot we are having annoying `npm audit` problems that I would like to resolve. Thank you for your time! :)

**Comment by cancan101** [comment]
following up here and wondering if the package will be published under the `@node-oauth` org on npm?

**Comment by casret** [comment]
Yep would also like for this to published.

**Comment by jankapunkt** [comment]
Hey @relu91 @cancan101 @casret I did not watch the repo to I totally missed these comments. There are some other comments as well in the main repo asking for this.

I would go an extra round and look for updating this repo. However, I do not actively use the oauth2 server with express so I need a bit of your requirements on what actually needs to be updated.

**Comment by jankapunkt** [comment]
@relu91 @cancan101 @casret please review this PR: #7 The more reviewers we have the faster we can publish

**Comment by relu91** [comment]
Thank you for pinging me back. As I said in the beginning our main use case is to have a test server that is fully compliant with oAuth2 protocol to verify that our client is behaving correctly. I'll check #7

**Comment by jankapunkt** [comment]
I got it reviewed from one maintainer of our org who uses express plus from an external so I published the updated version with no audit issues (updated dependencies) and the new OAuth2 server from this org.

It's available from npm via: https://www.npmjs.com/package/@node-oauth/express-oauth-server

**Comment by relu91** [comment]
I'll try ASAP and I'll let you know.

**Comment by cancan101** [comment]
How do I get typescript to see the types for this new package? When I had previously installing this package from GitHub, I had been using this package `@types/express-oauth-server` to add types. Now that I am installing from npm using `@node-oauth/express-oauth-server`, typescript is no longer seeing the types.

**Comment by jankapunkt** [comment]
The types were related to the original repo. Since we didn't change the API it should work if we create a types.ts file and copy the one from the types repo, right?

**Comment by jankapunkt** [comment]
@cancan101 @relu91 the types would be added in this PR: #11 please review and confirm/deny so we can merge and move forward with this :-)

**Comment by relu91** [comment]
Everything was fine, thank you really much!
